# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f10ba92dbc56c6cf61b78de8325f7d48b51757b8d27ad56efcdf44c5baa967f64e0effdac9b8075a7732eb585ba2464a9d964bb32fd34f82956b4183e07513

test:
  secret_key_base: 9bf4f899ca5ea338537f0e350a64056b963d8896157fdc18ea639cc439012a92987e7155cd118764385151b0bac9a31d04be01e458188dc4b9dac3f5bcc46d28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
